<?php $this->headTitle('Project Details');?>
<div class="pageheader">
	<h2>
		<i class="fa fa-user"></i> Project <span>Details</span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li><a href="<?php echo $this->basePath('user/project');?>">Project</a></li>
			<li class="active">Details</li>
		</ol>
	</div>
</div>
  <?php if($this->messages) {
        
       echo '<div class="panel-body"><div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->messages[0].'
        </div></div>';
    }
     if($this->error_messages) {
        
       echo '<div class="panel-body"><div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->error_messages[0].'
        </div></div>';
    } 
    //echo "<pre>";
    //print_r($this->projects); die;
    ?>      
<div class="contentpanel">
      
      <div class="row">
        <div class="col-sm-3">
           <?php if (!empty($this->details->data->vc_logo) && file_exists ( 'public/uploads/userImages/'.$this->details->data->vc_logo)) :?>
				<img src="<?php echo $this->basePath('uploads/userImages/'.($this->details->data->vc_logo));?>" class="thumbnail img-responsive">
          <?php  else : ?>
			  <img src="<?php echo $this->basePath('images/photos/profile-1.png');?>" class="thumbnail img-responsive">
			<?php endif;?>
          <div class="mb30"></div>  
        </div><!-- col-sm-3 -->
        <style>.companynamet span{ color:#333;}
        .profileWhiteDiv{ width:100%; padding:10px; background:#fff;}
        </style>
        <div class="col-sm-9">
          
          <div class="profile-header">
            <h2 class="profile-name"><?php echo $this->projects['vc_name']; ?></h2>
            <div class="">
            	<h4 class="text-primary companynamet"><span>Company -</span> <?php echo $this->details->data->vc_company_name; ?></h4>
            </div>
            <div class="profileWhiteDiv">
			<div class="profile-position">Business Unit - <span class="text-success"> <a href="<?php echo $this->url('businessunit', array('action' => 'bussinessunitdetails', 'slug' =>$this->projects['i_ref_bu_id'])); ?>"><?php echo $this->projects['vc_short_name']; ?></a></span></div>
             <div class="profile-position">Status - <span class="text-success"> <?php echo ($this->projects['i_status']==1?'Activated':'Deactivated'); ?></span></div>
            <div class="profile-location"><i class="fa fa-calendar"></i> Created date - <?php echo date("Y-m-d", strtotime($this->projects['dt_created'])); ?></div>
            <div class="profile-position"><i class="fa fa-calendar"></i> Last modified date - <?php echo date("Y-m-d", strtotime($this->projects['dt_modified'])); ?></div>
            
            <div class="mb20"></div>
            <h5 class="subtitle mb10">About</h5>
            <p class="mb10"><?php echo $this->projects['vc_description']; ?></p>
            </div>
            <div class="mb20"></div>
            
            <button class="btn btn-success mr5" onclick="window.print();"><i class="fa fa-print"></i> Print this page</button>
           
          </div><!-- profile-header -->
        </div>
        </div>
        <div class="mb20"></div>
        <!-- tab-content -->
        </div><!-- col-sm-9 -->
      </div><!-- row -->
<?php 
    $this->inlineScript ()->prependFile ( $this->basePath () . '/js/common/common.js' );
    $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/businessunit.js' );
?>
