<?php $this->headTitle('Users');?>
<div class="pageheader">
	<h2>
		<i class="fa fa-user"></i> Projects <span>Listing</span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li class="active">Projects</li>
			<li><a href="<?php echo BASE_URL; ?>user/project/addproject" class="btn btn-success btn-xs">Add New Projects</a></li>
		</ol>
	</div>
</div>
  <?php if($this->messages) {
        
       echo '<div class="panel-body"><div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->messages[0].'
        </div></div>';
    }
     if($this->error_messages) {
        
       echo '<div class="panel-body"><div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->error_messages[0].'
        </div></div>';
    } ?>      
<div class="contentpanel">
	<!-- content goes here... -->
    <div class="table-responsive">
          <table class="table" id="tableUsers">
              <thead>
                 <tr>
                    <th>S.No</th> 
                    <th>Name</th>
                    <th>Status</th>
                    <th class="table-action">Details</th>
                    <th class="table-action">Edit</th>
                 </tr>
              </thead>
               
              <tbody>
               <?php  
					$projectSerial=1;$projectList="";
					if(is_array($this->projectList)) {
 					foreach($this->projectList as $project) {
						
 						$projectList .= '<tr class="gradeU">';
						$projectList .= '<td>'.$projectSerial++.'</td>';
 						 $projectList .= '<td class="center"> '.$project['vc_name'].'</td>';

 						if($project['i_status']=='1') {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_green.png"  alt="Deactive" data-original-title="Active , click here to deactivate">';
 						 } else {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_red.png"  alt="Deactive" data-original-title="De-active , click here to Activate">';
				
 						 }
 						 $projectList .= '<td class="center"><a href="javascript:;" class="activeDeactive" 
                                             data-id='.$project['i_project_id'].' data-type="projects" data-field="i_project_id" data-status='.$project['i_status'].'>'.$statusImage.'</a></td>';
 						 $projectList .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/project/projectdetails/'.$project['i_project_id'].'" alt="Details" title="Details"><i class="glyphicon glyphicon-folder-open"></i></a>
 										</td>';
 						 $projectList .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/project/addproject/'.$project['i_project_id'].'" alt="Edit" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
 										</td>';
 						 $projectList .= '</tr>';  
 					}
					} else {
					    $projectList= "<tr><td></td><td></td><td>No Record to List</td><td></td><td></td></tr>";
					    
					}
 					echo $projectList;
				?> 
              </tbody>
           </table>
          </div><!-- table-responsive -->
</div>
<?php 
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/common/common.js' );
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/project.js' );
?>
