<?php $this->headTitle(($this->i_bu_id ? 'Edit Business Unit' : 'Add Business Unit')); 

if(isset($this->businessunit['business_departments']) and !empty($this->businessunit['business_departments'])) {
   $departments=$this->businessunit['business_departments'];
   $departmentsarray = array_map(function ($departments) { return $departments['i_ref_dep_id']; }, $departments);
} else {
   $departmentsarray=array();
}

?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Business Unit <span><?php echo ($this->i_bu_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">User</a></li>
			<li><a href="<?php echo $this->basePath('user/businessunit');?>">Business Unit</a></li>
			<li class="active"><?php echo ($this->businessunit_id ? 'Edit' : 'Add'); ?> Business Unit</li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <!-- a href="" class="panel-close">&times;</a -->
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->i_bu_id ? 'Edit' : 'Add'); ?> Business Unit</h4>
        </div>
		 <form id="addBusinessunitForm" name="addBusinessunitForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->i_bu_id ? '<input type="hidden" value="'.$this->i_bu_id.'" name="i_bu_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Name<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Name" class="form-control" name="vc_short_name" id="vc_short_name" value="<?php echo $this->businessunit['vc_short_name'];?>"/>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-3 control-label">Legal Name</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Legal Name" class="form-control" name="vc_legal_name" id="vc_legal_name" value="<?php echo $this->businessunit['vc_legal_name'];?>"/>
              </div>
            </div>
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-9">
               
               <textarea id="description" name="vc_description" placeholder="Enter description here..." class="form-control" rows="5"><?php echo $this->businessunit['vc_description'];?></textarea>
              
              </div>
            </div>  
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Comments</label>
              <div class="col-sm-9">
               
               <textarea id="vc_comments" name="vc_comments" 
               placeholder="Enter comments here..." class="form-control" rows="5"><?php echo $this->businessunit['vc_comments'];?></textarea>
              
              </div>
            </div>  
            <div class="form-group">  
             <label class="col-sm-3 control-label">Address</label>
              <div class="col-sm-9">
               <textarea id="vc_street_address" name="vc_street_address" 
               placeholder="Enter address here..." class="form-control" rows="5"><?php echo $this->businessunit['vc_street_address'];?></textarea>
              </div>
            </div>
            <?php if(is_array($this->departments) AND count($this->departments)>0) { ?>  
            <div class="form-group">
              <label class="col-sm-3 control-label">Departments</label>
               <div class="col-sm-9">
               <?php foreach($this->departments as $departments) { ?>
                    <div class="col-sm-3">
                        <div class="checkbox block">
                            <label><input name="departments[]" type="checkbox" value="<?php echo $departments['i_dep_id']; ?>"
                            <?php if(in_array($departments['i_dep_id'], $departmentsarray)) {
                                echo "checked='checked'";
                            } ?>
                            > <?php echo $departments['vc_name']; ?></label>
                        </div>
                    </div>
               <?php } ?>
            </div>
			</div>
		  <?php } ?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="i_status" name="i_status">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->businessunit['i_status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->i_bu_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->i_bu_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/businessunit');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/businessunit.js' );
?>
