<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Forgot Password</title>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,600,700,300|Roboto:500,400italic,300,700,500italic,300italic,400' rel='stylesheet' type='text/css'>
<style type="text/css">
	body{ font-family: 'Roboto', Arial, Helvetica, sans-serif; }
</style>
</head>

<body bgcolor="#8d8e90">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#333">
  <tr>
    <td><table width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#fffff" align="center" >
      
        <tr>
          <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="100%"><img src="<?php echo BASE_URL.'images/emailHeader.jpg';?>" alt="LOGO" width="100%" border="0" /></td>
              </tr>
            </table></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="5%">&nbsp;</td>
                <td width="90%" align="left" valign="top">
                <font style="color:#45c8dc; font-size:24px"><strong style="font-weight:500"><em>Hi 
                <?php 
                if(isset($this->username)){
                	echo $this->username;
                }
                ?>,</em></strong></font><br /><hr style=" border-color:#BFBFBF" /><br />
                  <font style="font-family: 'Open Sans',arial,  sans-serif; color:#3b3b3b; font-size:20px; line-height:24px">
                  	<strong style="margin-bottom:15px; display:inline-block; font-weight:500">Reset your password</strong>
                  </font>
                  <br />
                  <font style="font-family: 'Open Sans', arial, sans-serif; color:#3b3b3b; font-size:13px; line-height:21px">
                  Just click "Reset Now" to reset your password. 
<br />	
</font>
<center>
	<a href="<?php echo $this->resetLink;?>" style=" color:#fff; font-size:18px; line-height:30px; text-decoration:none; padding:10px 15px; display:inline-block; background:#45c8dc; margin:15px 0;">Reset Now</a>
</center>
<font style="font-family: 'Open Sans', sans-serif; color:#fff; font-size:13px; line-height:21px">
Thanks &amp; Regards,<br />
Budget And Purcahse</font></td>
                <td width="5%">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td align="right" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
                  <tr>
                    <td align="center"><br /><font style="font-family: 'Open Sans', sans-serif; color:#3b3b3b; font-size:13px; line-height:21px"><i>Need help? Have feedback? Feel free to email us at <a href="#" style=" color:#45c8dc">info@budgetandpurchase.com</a></i></font><br /><br /></td>
                  </tr>
                  
                </table>
                </td>
                <td>&nbsp;</td>
              </tr>
            </table></td>
        </tr>
        
        <tr>
          <td>&nbsp;</td>
        </tr>
       
        <tr>
          <td><table width="100%" border="0" cellspacing="0" cellpadding="0" style="font-family: 'Open Sans', Arial, sans-serif"  bgcolor="#eee">
          	<tr>
            	<td colspan="3">&nbsp;
                
                </td>
            
            </tr>
             </table></td>
        </tr>
        <tr>
          <td bgcolor="#eee">&nbsp;</td>
        </tr>
      </table></td>
  </tr>
</table>
</body>
</html>