<?php $this->headTitle(($this->department_id ? 'Edit User' : 'Add User')); ?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Add User <span><?php echo ($this->user_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('user');?>">User</a></li>
			<li class="active"><?php echo ($this->user_id ? 'Edit' : 'Add'); ?> User</li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <!-- a href="" class="panel-close">&times;</a -->
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->user_id ? 'Edit' : 'Add'); ?> User</h4>
        </div>
		 <form id="addUserForm" name="addUserForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->user_id ? '<input type="hidden" value="'.$this->user_id.'" name="user_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Email<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Email" class="form-control" name="email" id="email" value="<?php echo $this->user['email'];?>"/>
              </div>
            </div>
            <div id="businessgroup">
            <div class="form-group">
              <label class="col-sm-2 control-label">Business Unit<span class="asterisk">*</span></label>
              <div class="col-sm-2">
                <select name="business_unit[]"  class="form-control mb15 business_unit">
					<option value="">Select Business Unit</option>
					<?php if(isset($this->businessunit) && is_array($this->businessunit)) {
						foreach($this->businessunit as $businessunit) {
								echo "<option value='".$businessunit['i_bu_id']."'>".$businessunit['vc_short_name']."</option>";
						}
					} ?>
					
				</select>
              </div>
              <label class="col-sm-1 control-label">Department<span class="asterisk">*</span></label>
              <div class="col-sm-2">
                <select name="department[]" class="form-control mb15 departments">
					<option value="">Select Business Unit First</option>
				</select>
              </div>
              <label class="col-sm-1 control-label">Role<span class="asterisk">*</span></label>
              <div class="col-sm-2">
                <select name="role[]" class="form-control mb15 role">
					<option value="">Select Role</option>
					<?php if(isset($this->roles) && is_array($this->roles)) {
						foreach($this->roles as $roles) {
								echo "<option value='".$roles['i_role_id']."'>".$roles['vc_name']."</option>";
						}
					} ?>
				</select>
              </div>
				<div class="col-sm-1"><button type="button" class="btn btn-primary addmore">Add More</button></div>
              </div>
             </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->user_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addUserBtn" name="addUserBtn" value="<?php echo ($this->page_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php
	
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/users.js' );
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/common/common.js' );
?>
