<?php $this->headTitle('Users');?>
<div class="pageheader">
	<h2>
		<i class="fa fa-user"></i> Levels <span>Listing</span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li class="active">Users</li>
			<li><a href="<?php echo BASE_URL; ?>user/adduser" class="btn btn-success btn-xs">Add New User</a></li>
		</ol>
	</div>
</div>
  <?php 
 
	if($this->messages) {
        
       echo '<div class="panel-body"><div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->messages[0].'
        </div></div>';
    }
     if($this->error_messages) {
        
       echo '<div class="panel-body"><div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->error_messages[0].'
        </div></div>';
    } ?>     
<div class="contentpanel">
	<!-- content goes here... -->
    <div class="table-responsive">
          <table class="table" id="tableUsers">
              <thead>
                 <tr>
                    <th>S.No</th> 
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th></th>
                 </tr>
              </thead>
               
              <tbody>
               <?php  
					$Serial=1;$Listing="";
					if(is_array($this->userList)) {
 					foreach($this->userList as $userList) {
						
						if($userList['i_cu_status']=='1') {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_green.png"  alt="Deactive" data-original-title="Active , click here to deactivate">';
 						 } else {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_red.png"  alt="Deactive" data-original-title="De-active , click here to Activate">';
				
 						 }
 						 
 						$Listing .= '<tr class="gradeU">';
						$Listing .= '<td>'.$Serial++.'</td>';
 						$Listing .= '<td class="center"> '.$userList['vc_fname'].' '.$userList['vc_lname'].'</td>';
 						$Listing .= '<td class="center"> '.$userList['vc_email'].'</td>';
 						$Listing .= '<td class="center"><a href="javascript:;" class="activeDeactiveCompanyUser" 
                                             data-id='.$userList['i_ref_company_id'].' data-field="i_ref_company_id" data-id-1='.$userList['i_user_id'].' data-field-1="i_ref_user_id" data-type="user_details" data-status='.$userList['i_cu_status'].'>'.$statusImage.'</a></td>';
						if($userList['activate_token']!="") {
							$accountstatus="Email not confirmed";
						} else {
							$accountstatus="Email confirmed";
						}
 						 $Listing .= '<td class="center">'.$accountstatus.'</td>';
 						 $Listing .= '</tr>';  
 					}
					} else {
					    $Listing= "<tr><td colspan=4>No Record to List</td></tr>";
					    
					}
 					echo $Listing;
				?> 
              </tbody>
           </table>
          </div><!-- table-responsive -->
</div>
<?php 
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/common/common.js' );
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/users.js' );

?>
