<?php $this->headTitle(($this->costcenter_id ? 'Edit Cost Center' : 'Add Cost Center'));

	
?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Cost Center <span><?php echo ($this->costcenter_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('user');?>">User</a></li>
			<li><a href="<?php echo $this->basePath('user/costcenter');?>">Cost Center</a></li>
			<li class="active"><?php echo ($this->costcenter_id ? 'Edit' : 'Add'); ?></li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <a href="" class="panel-close">&times;</a>
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->costcenter_id ? 'Edit' : 'Add'); ?> Cost Center</h4>
        </div>
		 <form id="addCostcenterForm" name="addCostcenterForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->costcenter_id ? '<input type="hidden" value="'.$this->costcenter_id.'" name="costcenter_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Title</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="title" id="title" value="<?php echo $this->costcente['title'];?>"/>
              </div>
            </div>
			<div class="form-group">
              <label class="col-sm-3 control-label">Code</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Code" class="form-control" name="code" id="code" value="<?php echo $this->costcente['code'];?>"/>
              </div>
            </div>
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Budget ($)</label>
              <div class="col-sm-3">
                <input type="text" placeholder="Enter Budget" class="form-control" name="budget" id="budget" value="<?php echo $this->costcente['budget'];?>"/>
              </div>
              
            </div>  
			<div class="form-group">
              
             <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-6">
                <textarea placeholder="Enter Description" class="form-control" name="description" id="description"><?php echo $this->costcente['description'];?></textarea>
              </div>
            
            </div>
			<?php if(is_array($this->parentcostcenter)) { ?>  
            <div class="form-group">
             <label class="col-sm-3 control-label">Parent Cost Center</label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="parent_id" name="parent_id">
				        <option value="0"> Select Parent Cost Center (if any) </option>
						<?php
							foreach($this->parentcostcenter as $parentcostcenter) {
								echo "<option value=".$parentcostcenter['id'];
								if($parentcostcenter['id']==$this->costcente['parent_id']) { echo " selected='selected'"; }
								echo ">".$parentcostcenter['title']."</option>";
							}
						?>
				   </select>
              </div>
            </div>
            <?php } else {
				echo '<input type="hidden" name="parent_id" value="0">';
			} ?>			
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="pstatus" name="status">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->costcente['status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->costcenter_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->costcenter_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/level');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php 
   $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/costcenter.js' );
?>