<?php $this->headTitle(($this->i_cc_id ? 'Edit Cost Center' : 'Add Cost Center'));

	if(isset($this->costcente['costcenter_costgroup']) and !empty($this->costcente['costcenter_costgroup'])) {
		$costgroup=$this->costcente['costcenter_costgroup'];
		$costgrouparray = array_map(function ($costgroup) { return $costgroup['i_ref_ccgroup_id']; }, $costgroup);
	} else {
		$costgrouparray=array();
	}
	
?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Cost Center <span><?php echo ($this->i_cc_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li><a href="<?php echo $this->basePath('user/costcenter');?>">Cost Center</a></li>
			<li class="active"><?php echo ($this->i_cc_id ? 'Edit' : 'Add'); ?> Cost Center</li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
           <!-- a href="" class="panel-close">&times;</a -->
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->i_cc_id ? 'Edit' : 'Add'); ?> Cost Center</h4>
        </div>
		 <form id="addCostcenterForm" name="addCostcenterForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->i_cc_id ? '<input type="hidden" value="'.$this->i_cc_id.'" name="i_cc_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Name<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="vc_name" id="vc_name" value="<?php echo $this->costcente['vc_name'];?>"/>
              </div>
            </div>
			<div class="form-group">
              <label class="col-sm-3 control-label">Account number<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Account number" class="form-control" name="vc_account_number" id="vc_account_number" value="<?php echo $this->costcente['vc_account_number'];?>"/>
              </div>
            </div>
			<div class="form-group">
              <label class="col-sm-3 control-label">Type</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Type"  
                class="form-control" name="vc_type" id="vc_type" value="<?php echo $this->costcente['vc_type'];?>"/>
              </div>
            </div>
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Budget ($)<span class="asterisk">*</span></label>
              <div class="col-sm-3">
                <input type="text" placeholder="Enter Budget" class="form-control" name="i_budget" id="i_budget" value="<?php echo $this->costcente['i_budget'];?>"/>
              </div>
              
            </div>  
			<div class="form-group">
              
             <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-6">
                <textarea placeholder="Enter Description" class="form-control" name="vc_description" id="vc_description"><?php echo $this->costcente['vc_description'];?></textarea>
              </div>
            
            </div>
			<?php if(is_array($this->cost_group) AND count($this->cost_group)>0) { ?>  
            <div class="form-group">
              <label class="col-sm-3 control-label">Cost Group</label>
              
               <?php foreach($this->cost_group as $cost_group) { ?>
                    <div class="col-sm-2">
                        <div class="checkbox block">
                            <label><input name="cost_group[]" type="checkbox" value="<?php echo $cost_group['i_ccgroup_id']; ?>"
                            <?php if(in_array($cost_group['i_ccgroup_id'], $costgrouparray)) {
                                echo "checked='checked'";
							} ?>
                            > <?php echo $cost_group['vc_account_group']; ?></label>
                        </div>
                    </div>
               <?php } ?>
            </div>
		  <?php } ?>			
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="i_status" name="i_status">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->costcente['i_status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->i_cc_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->i_cc_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/level');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php 
   $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/costcenter.js' );
?>
