<?php $this->headTitle(($this->i_ccgroup_id ? 'Edit Cost Center' : 'Add Cost Center'));

	if(isset($this->costcentegroup['costcenter_costgroup']) and !empty($this->costcentegroup['costcenter_costgroup'])) {
		$costcenter=$this->costcentegroup['costcenter_costgroup'];
		$costcenterarray = array_map(function ($costcenter) { return $costcenter['i_ref_cc_id']; }, $costcenter);
	} else {
		$costcenterarray=array();
	}
	
?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Cost Center Group <span><?php echo ($this->i_ccgroup_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li><a href="<?php echo $this->basePath('user/ccgroup');?>">Cost Center Group</a></li>
			<li class="active"><?php echo ($this->costcenter_group_id ? 'Edit' : 'Add'); ?> Cost Center Group</li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <!-- a href="" class="panel-close">&times;</a -->
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->i_ccgroup_id ? 'Edit' : 'Add'); ?> Cost Center Group </h4>
        </div>
		 <form id="addCostcentergroupForm" name="addCostcentergroupForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->i_ccgroup_id ? '<input type="hidden" value="'.$this->i_ccgroup_id.'" name="i_ccgroup_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Title<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="vc_account_group" id="vc_account_group" value="<?php echo $this->costcentegroup['vc_account_group'];?>"/>
              </div>
            </div>
			<div class="form-group">
              
             <label class="col-sm-3 control-label">Cost Center<span class="asterisk">*</span></label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="costcenter_costgroup" name="costcenter_costgroup[]" multiple="multiple">
						<?php
							if(is_array($this->cost_center) ) {
								foreach($this->cost_center as $costcenter) {
									echo "<option value=".$costcenter['i_cc_id'];
									if(in_array($costcenter['i_cc_id'],$costcenterarray)) { echo " selected='selected'"; }
									echo ">".$costcenter['vc_name']."</option>";
								}
							}
						?>
				   </select>
              </div>
            </div> 	
			<div class="form-group">
             <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-6">
                <textarea placeholder="Enter Description" class="form-control" name="vc_description" id="vc_description"><?php echo $this->costcentegroup['vc_description'];?></textarea>
              </div>
            </div>
						
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="i_status" name="i_status">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->costcente['i_status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->i_ccgroup_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->i_ccgroup_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/level');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php 
   $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/ccgroup.js' );
?>
