<?php $this->headTitle('Users');?>
<div class="pageheader">
	<h2>
		<i class="fa fa-user"></i> Cost Center Groups <span>Listing</span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li class="active">Cost Center Groups </li>
			<li><a href="<?php echo BASE_URL; ?>user/ccgroup/addccgroup" class="btn btn-success btn-xs">Add New Cost Center Group</a></li>
		</ol>
	</div>
</div>
  <?php if($this->messages) {
        
       echo '<div class="panel-body"><div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->messages[0].'
        </div></div>';
    }
     if($this->error_messages) {
        
       echo '<div class="panel-body"><div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->error_messages[0].'
        </div></div>';
    } ?>     
<div class="contentpanel">
	<!-- content goes here... -->
    <div class="table-responsive">
          <table class="table" id="tableUsers">
              <thead>
                 <tr>
                    <th>S.No</th> 
                    <th>Title</th>
                    <th>Status</th>
                    <th class="table-action">Details</th>
                   <th class="table-action">Edit</th>
                 </tr>
              </thead>
               
              <tbody>
               <?php  
					$Serial=1;$Listing="";
					if(is_array($this->ccgroupList)) {
 					foreach($this->ccgroupList as $costcenterList) {
						
 						$Listing .= '<tr class="gradeU">';
						$Listing .= '<td>'.$Serial++.'</td>';
 						 $Listing .= '<td class="center"> '.$costcenterList['vc_account_group'].'</td>';

 						if($costcenterList['i_status']=='1') {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_green.png"  alt="Deactive" data-original-title="Active , click here to deactivate">';
 						 } else {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_red.png"  alt="Deactive" data-original-title="De-active , click here to Activate">';
				
 						 }
 						 $Listing .= '<td class="center"><a href="javascript:;" class="activeDeactive" 
                                             data-id='.$costcenterList['i_ccgroup_id'].' data-type="cost_group" data-field="i_ccgroup_id" data-status='.$costcenterList['i_status'].'>'.$statusImage.'</a></td>';
 						 $Listing .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/ccgroup/ccgroupdetails/'.$costcenterList['i_ccgroup_id'].'" alt="Details" title="Details"><i class="glyphicon glyphicon-folder-open"></i></a>
 										</td>';
 						 $Listing .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/ccgroup/addccgroup/'.$costcenterList['i_ccgroup_id'].'" alt="Edit" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
 										</td>';
 						 $Listing .= '</tr>';  
 					}
					} else {
					    $Listing= "<tr><td></td><td></td><td>No Record to List</td><td></td><td></td></tr>";
					    
					}
 					echo $Listing;
				?> 
              </tbody>
           </table>
          </div><!-- table-responsive -->
</div>
<?php 
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/common/common.js' );
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/ccgroup.js' );
?>
