<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('Budget & Purchase - '. $this->translate('Admin'))->setSeparator(' - ')->setAutoEscape(false)?>
   		<?php
    
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
    <meta name="description" content="">
<meta name="author" content="">


<!-- Le styles -->
        <?php
        
echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/images/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.default.css')
			->prependStylesheet($this->basePath () . '/css/jquery.datatables.css' )
			->prependStylesheet($this->basePath () . '/css/developer.css' );
        ?>
		
		
        <?php
        
echo $this->headScript()
            -> // IE10 viewport hack for Surface/desktop Windows 8 bug
prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>
  </head>

<body>

<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<section>
  
  <div class="leftpanel">
    
    <div class="logopanel">
        <h1><?php echo $this->userSession->data->vc_company_name; ?></h1>
    </div><!-- logopanel -->
    
    <div class="leftpanelinner">
        
        <!-- This is only visible to small devices -->
        <div class="visible-xs hidden-sm hidden-md hidden-lg">   
            <div class="media userlogged">
				<img alt="" src="<?php echo $this->basepath('images/photos/loggeduser.png');?>" class="media-object">
                <div class="media-body">
                    <h4><?php echo ucfirst($this->userSession->data->vc_fname).' '.ucfirst($this->userSession->data->vc_lname); ?></h4>
                </div>
            </div>
          
            <h5 class="sidebartitle actitle">Account</h5>
            <ul class="nav nav-pills nav-stacked nav-bracket mb30">
              <li><a href="<?php echo $this->basepath('authenticate/logout');?>"><i class="fa fa-sign-out"></i> <span>Sign Out</span></a></li>
            </ul>
        </div>
      
      <h5 class="sidebartitle">Navigation</h5>
      <ul class="nav nav-pills nav-stacked nav-bracket">

        <li <?php echo  ($this->url() == '/user' || $this->url() == '/user/dashboard')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/dashboard');?>"><i class="fa fa-home"></i> <span>Dashboard</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/businessunit')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/businessunit');?>"><i class="fa fa-briefcase"></i> <span>Business Units</span></a>
		</li>
        <li <?php echo ($this->serverUrl(true) == BASE_URL.'user/department')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/department');?>"><i class="fa fa-building-o"></i> <span>Departments</span></a>
		</li>
	<!--	<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/location')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/location');?>"><i class="fa fa-location-arrow"></i> <span>Locations</span></a>
		</li>
	-->	
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/project')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/project');?>"><i class="fa fa-envelope"></i> <span>Projects</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/wbs')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/wbs');?>"><i class="fa fa-group"></i> <span>WBS</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/costcenter')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/costcenter');?>"><i class="fa fa-envelope"></i> <span>Cost Center</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/ccgroup')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/ccgroup');?>"><i class="fa fa-envelope"></i> <span>Cost Center Groups</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/level')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/level');?>"><i class="fa fa-sitemap"></i> <span>Levels</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/role')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/role');?>"><i class="fa fa-sitemap"></i> <span>Roles</span></a>
		</li>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/group')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/group');?>"><i class="fa fa-group"></i> <span>Groups</span></a>
		</li>
		<?php if($this->userSession->type=="Company") { ?>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user');?>"><i class="fa fa-group"></i> <span>Users</span></a>
		</li>
		<?php } ?>
		<li <?php echo ($this->serverUrl(true) == BASE_URL.'user/purchaserequest')  ? 'class=active' : '';?>>
			<a href="<?php echo $this->basepath('/user/purchaserequest');?>"><i class="fa fa-group"></i> <span>Purchase Requests</span></a>
		</li>
      </ul>
      </div>
    </div>

  <div class="mainpanel">
    
    <div class="headerbar">
      
      <a class="menutoggle"><i class="fa fa-bars"></i></a>
		<!-- <?php if($this->userSession->type=='Employee') { 	 ?>
		  <?php if(isset($this->userSession->usercompanies)) { ?>
			<div class="col-sm-5"><select class="form-control mb15">
				<?php foreach($this->userSession->usercompanies as $usercompanies) { ?>
					<option <?php if($this->userSession->data->i_company_id==$usercompanies['i_ref_company_id']) {
								echo "selected=selected"; } ?> class="changecompany" data-companyid=<?php echo $usercompanies['i_ref_company_id']; ?>><?php echo $usercompanies['vc_company_name']; ?>
						</option>
					<?php } ?>
                </select></div>
			<?php } ?>
         <?php } ?> -->
      <div class="header-right">
		  
         
        <ul class="headermenu">
		 <?php if($this->userSession->type=='Employee') { 	 ?>
			 <li>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <img src="<?php echo $this->basepath('images/photos/loggeduser.png');?>" alt="" />
                <?php echo 'Companies'; ?>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                <?php if(isset($this->userSession->usercompanies)) {
					foreach($this->userSession->usercompanies as $usercompanies) { ?>
						<li
						<?php if($this->userSession->data->i_company_id==$usercompanies['i_ref_company_id']) {
								echo "class='companyselected'";
							}
						?>
						><a href="javascript:;" class="changecompany" data-companyid=<?php echo $usercompanies['i_ref_company_id']; ?> data-companyname="<?php echo $usercompanies['vc_company_name']; ?>"><i class="glyphicon glyphicon-log-out"></i> <?php echo $usercompanies['vc_company_name']; ?></a></li>
				<?php }
				} ?>
              </ul>
            </div>
          </li>
          <?php } ?>
          <li>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <img src="<?php echo $this->basepath('images/photos/loggeduser.png');?>" alt="" />
                <?php echo ucfirst($this->userSession->data->vc_fname).' '.ucfirst($this->userSession->data->vc_lname); ?>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
				  <li><a href="<?php echo $this->basepath('user/profile');?>"><i class="glyphicon glyphicon-user"></i> My Profile</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-cog"></i> Account Settings</a></li>
                <li><a href="<?php echo $this->basepath('authenticate/logout');?>"><i class="glyphicon glyphicon-log-out"></i> Log Out</a></li>
              </ul>
            </div>
          </li>
        </ul>
      </div><!-- header-right -->
    </div><!-- headerbar -->
    <?php echo $this->content;?>
  </div><!-- mainpanel -->
</section>



<?php
echo $this->inlineScript()
	->prependFile($this->basePath() . '/js/common/common.js')
    ->prependFile($this->basePath() . '/js/customFormValidators.js' )
    ->prependFile($this->basePath() . '/js/chosen.jquery.min.js' )
    ->prependFile($this->basePath() . '/js/jquery.datatables.min.js' )
	->prependFile($this->basePath() . '/js/jquery.validate.js' )
    ->prependFile($this->basePath() . '/js/custom.js')
    ->prependFile($this->basePath() . '/js/jquery.cookies.js')
    ->prependFile($this->basePath() . '/js/retina.min.js')
    ->prependFile($this->basePath() . '/js/toggles.min.js')
    ->prependFile($this->basePath() . '/js/jquery.sparkline.min.js')
    ->prependFile($this->basePath() . '/js/modernizr.min.js')
    ->prependFile($this->basePath() . '/js/bootbox.min.js' )
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery-migrate-1.2.1.min.js')
    ->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js');
?>

</body>
</html>
