<?php $this->headTitle(($this->i_role_id ? 'Edit Role' : 'Add Role'));

	if(isset($this->role['roles_permission']) and !empty($this->role['roles_permission'])) {
		$role_permission=$this->role['roles_permission'];
		$role_permissionarray = array_map(function ($role_permission) { return $role_permission['i_ref_permission_id']; }, $role_permission);
	} else {
		$role_permissionarray=array();
	}
?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Role <span><?php echo ($this->i_role_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li><a href="<?php echo $this->basePath('user/role');?>">Role</a></li>
			<li class="active"><?php echo ($this->role_id ? 'Edit' : 'Add'); ?> Role</li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <!-- a href="" class="panel-close">&times;</a -->
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->i_role_id ? 'Edit' : 'Add'); ?> Role</h4>
        </div>
		 <form id="addRoleForm" name="addRoleForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->i_role_id ? '<input type="hidden" value="'.$this->i_role_id.'" name="i_role_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Name<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Name" class="form-control" name="vc_name" id="title" value="<?php echo $this->role['vc_name'];?>"/>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-6">
                <textarea placeholder="Enter Description" class="form-control" name="vc_description" id="vc_description"><?php echo $this->role['vc_description'];?></textarea>
              </div>
            </div>
            <div class="form-group">
             <label class="col-sm-3 control-label">Level<span class="asterisk">*</span></label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="i_ref_limit_id" name="i_ref_limit_id">
						<?php
							foreach($this->levels as $level) {
								echo "<option value=".$level['i_level_id'];
								if($level['i_level_id']==$this->role['i_ref_limit_id']) { echo " selected='selected'"; }
								echo ">".$level['vc_name']."</option>";
							}
						?>
				   </select>
              </div>
            </div>  
			<div class="form-group">
              
             <label class="col-sm-3 control-label">Permissions<span class="asterisk">*</span></label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="roles_permission" name="roles_permission[]" multiple="multiple">
						<?php
							foreach($this->permissions as $permission) {
								echo "<option value=".$permission['i_permission_id'];
								if(in_array($permission['i_permission_id'],$role_permissionarray)) { echo " selected='selected'"; }
								echo ">".$permission['vc_name']."</option>";
							}
						?>
				   </select>
              </div>
            </div> 
            <?php if(is_array($this->roles)) { ?>  
            <div class="form-group">
             <label class="col-sm-3 control-label">Parent Role</label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="i_ref_role_id" name="i_ref_role_id">
				        <option> Select Parent Role (if any) </option>
						<?php
							foreach($this->roles as $parentroles) {
								echo "<option value=".$parentroles['i_role_id'];
								if($parentroles['i_role_id']==$this->role['i_ref_role_id']) { echo " selected='selected'"; }
								echo ">".$parentroles['vc_name']."</option>";
							}
						?>
				   </select>
              </div>
            </div>
            <?php } else {
					echo "<input type='hidden' name='i_ref_role_id' value='0'>";
				} ?>			
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="i_status" name="i_status">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->role['i_status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->i_role_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->i_role_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/businessunit');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php 
   $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/role.js' );
?>
