<?php $this->headTitle('Users');?>
<div class="pageheader">
	<h2>
		<i class="fa fa-user"></i> Roles <span>Listing</span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li class="active">Roles</li>
			<li><a href="<?php echo BASE_URL; ?>user/role/addrole" class="btn btn-success btn-xs">Add New Role</a></li>
		</ol>
	</div>
</div>
  <?php if($this->messages) {
        
       echo '<div class="panel-body"><div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->messages[0].'
        </div></div>';
    }
     if($this->error_messages) {
        
       echo '<div class="panel-body"><div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->error_messages[0].'
        </div></div>';
    } ?>     
<div class="contentpanel">
	<!-- content goes here... -->
    <div class="table-responsive">
          <table class="table" id="tableUsers">
              <thead>
                 <tr>
                    <th>S.No</th> 
                    <th>Name</th>
                    <th>Status</th>
                    <th class="table-action">Details</th>
                   <th class="table-action">Edit</th>
                 </tr>
              </thead>
               
              <tbody class="treeview">
               <?php  
					$Serial=1;$Listing="";
					if(is_array($this->roleList)) {
						
 					foreach($this->roleList as $roleList) {
						if($roleList['i_role_id']!='1') {  $parentcalss="treegrid-parent-1"; } else { $parentcalss=""; }
 						$Listing .= '<tr class="gradeU treegrid-'.$roleList['i_role_id'].' '.$parentcalss.'" >';
						$Listing .= '<td>'.$Serial++.'</td>';
 						 $Listing .= '<td class="center"> '.$roleList['vc_name'].'</td>';

 						if($roleList['i_status']=='1') {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_green.png"  alt="Deactive" data-original-title="Active , click here to deactivate">';
 						 } else {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_red.png"  alt="Deactive" data-original-title="De-active , click here to Activate">';
				
 						 }
 						 $Listing .= '<td class="center"><a href="javascript:;" class="activeDeactive" 
                                             data-id='.$roleList['i_role_id'].' data-type="roles" data-field="i_role_id"  data-status='.$roleList['i_status'].'>'.$statusImage.'</a></td>';
 						 $Listing .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/role/roledetails/'.$roleList['i_role_id'].'" alt="Details" title="Details"><i class="glyphicon glyphicon-folder-open"></i></a>
 										</td>';
 						 $Listing .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/role/addrole/'.$roleList['i_role_id'].'" alt="Edit" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
 										</td>';
 						 $Listing .= '</tr>';  
 					}
					} else {
					    $Listing= "<tr><td></td><td></td><td>No Record to List</td><td></td><td></td></tr>";
					    
					}
 					echo $Listing;
				?> 
              </tbody>
           </table>
          </div><!-- table-responsive -->
</div>
<?php 
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/common/common.js' );
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/role.js' );


?>
