<?php $this->headTitle(($this->department_id ? 'Edit Department' : 'Add Department'));

	if(isset($this->department['business_department']) and !empty($this->department['business_department'])) {
		$businessunit=$this->department['business_department'];
		$businesunitarray = array_map(function ($businessunit) { return $businessunit['businessunit_id']; }, $businessunit);
	} else {
		$businesunitarray=array();
	}

?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Department <span><?php echo ($this->department_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('user');?>">User</a></li>
			<li><a href="<?php echo $this->basePath('user/department');?>">Department</a></li>
			<li class="active"><?php echo ($this->department_id ? 'Edit' : 'Add'); ?></li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <a href="" class="panel-close">&times;</a>
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->department_id ? 'Edit' : 'Add'); ?> Department</h4>
        </div>
		 <form id="addDepartmentForm" name="addDepartmentForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->department_id ? '<input type="hidden" value="'.$this->department_id.'" name="department_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Title</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="title" id="title" value="<?php echo $this->department['title'];?>"/>
              </div>
            </div>
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-9">
               
               <textarea id="description" name="description" placeholder="Enter description here..." class="form-control" rows="10"><?php echo $this->department['description'];?></textarea>
              
              </div>
            </div>   
		  <div class="form-group">
              
             <label class="col-sm-3 control-label">Business Unit</label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="businessunit" name="businessunit[]" multiple="multiple">
					
						<?php
							if(is_array($this->businessunit) ) {
								foreach($this->businessunit as $businessunit) {
									echo "<option value=".$businessunit['id'];
									if(in_array($businessunit['id'],$businesunitarray)) { echo " selected='selected'"; }
									echo ">".$businessunit['title']."</option>";
								}
							}
						?>
				   </select>
              </div>
            </div> 	
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="pStatus" name="pStatus">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->department['status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->department_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->page_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/department');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/department.js' );
?>