<?php $this->headTitle('Users');?>
<div class="pageheader">
	<h2>
		<i class="fa fa-user"></i> Departments <span>Listing</span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('user');?>">Dashboard</a></li>
			<li class="active">Department</li>
			<li><a href="/user/department/adddepartment" class="btn btn-success btn-xs">Add New Department</a></li>
		</ol>
	</div>
</div>
    <?php if($this->messages) {
        
       echo '<div class="panel-body"><div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->messages[0].'
        </div></div>';
    }
     if($this->error_messages) {
        
       echo '<div class="panel-body"><div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        '.$this->error_messages[0].'
        </div></div>';
    } ?>      
<div class="contentpanel">
	<!-- content goes here... -->
    <div class="table-responsive">
          <table class="table" id="tableUsers">
              <thead>
                 <tr>
                    <th>S.No</th> 
                    <th>Title</th>
                    <th>Status</th>
                    <th class="table-action">Edit</th>
                 </tr>
              </thead>
               
              <tbody>
               <?php  
					$departmentSerial=1;$departmentListing="";
					if(is_array($this->departmentList)) {
 					foreach($this->departmentList as $department) {
						
 						$departmentListing .= '<tr class="gradeU">';
						$departmentListing .= '<td>'.$departmentSerial++.'</td>';
 						 $departmentListing .= '<td class="center"> '.$department['title'].'</td>';

 						if($department['status']=='1') {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_green.png"  alt="Deactive" data-original-title="Active , click here to deactivate">';
 						 } else {
 							$statusImage='<img data-tooltip="tooltip" src="'.$this->basePath ().'/images/status_red.png"  alt="Deactive" data-original-title="De-active , click here to Activate">';
				
 						 }
 						 $departmentListing .= '<td class="center"><a href="javascript:;" class="userstatus" 
                                             data-user-id='.$department['id'].' data-user-type="users" data-user-status='.$department['status'].'>'.$statusImage.'</a></td>';
 						 $departmentListing .= '<td class="table-action">
										  <a href="'.$this->basePath().'/user/department/adddepartment/'.$department['id'].'" alt="Edit" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
 										</td>';
 						 $departmentListing .= '</tr>';  
 					}
					} else {
					    $departmentListing= "<tr><td colspan=4>No Record to List</td></tr>";
					    
					}
 					echo $departmentListing;
				?> 
              </tbody>
           </table>
          </div><!-- table-responsive -->
</div>
<?php 
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/department.js' );
?>