<?php $this->headTitle(($this->level_id ? 'Edit Level' : 'Add Level'));

	if(isset($this->level['level_permission']) and !empty($this->level['level_permission'])) {
		$level_permission=$this->level['level_permission'];
		$level_permissionarray = array_map(function ($level_permission) { return $level_permission['permission_id']; }, $level_permission);
	} else {
		$level_permissionarray=array();
	}
?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Level <span><?php echo ($this->level_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('user');?>">User</a></li>
			<li><a href="<?php echo $this->basePath('user/level');?>">Level</a></li>
			<li class="active"><?php echo ($this->level_id ? 'Edit' : 'Add'); ?></li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <a href="" class="panel-close">&times;</a>
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->level_id ? 'Edit' : 'Add'); ?> Level</h4>
        </div>
		 <form id="addLevelForm" name="addLevelForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->level_id ? '<input type="hidden" value="'.$this->level_id.'" name="level_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Title</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="title" id="title" value="<?php echo $this->level['title'];?>"/>
              </div>
            </div>
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Budget ($)</label>
              <div class="col-sm-3">
                <input type="text" placeholder="Enter Minimum Budget" class="form-control" name="budget_min" id="budget_min" value="<?php echo $this->level['budget_min'];?>"/>
              </div>
              <div class="col-sm-3">
                <input type="text" placeholder="Enter Maximum Budget" class="form-control" name="budget_max" id="budget_max" value="<?php echo $this->level['budget_max'];?>"/>
              </div>
            </div>  
			<div class="form-group">
              
             <label class="col-sm-3 control-label">Permissions</label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="permission" name="permission[]" multiple="multiple">
						<?php
							foreach($this->permission as $permission) {
								echo "<option value=".$permission['id'];
								if(in_array($permission['id'],$level_permissionarray)) { echo " selected='selected'"; }
								echo ">".$permission['title']."</option>";
							}
						?>
				   </select>
              </div>
            </div>   			
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="pStatus" name="pStatus">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->level['status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->businessunit_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->businessunit_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/businessunit');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php 
   $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/level.js' );
?>