<?php
$title = 'Admin Login';
$this->headTitle ( $title );

$form = $this->form;
$form->setAttribute ( 'action', $this->url ( 'login/authenticate', array (
		'action' => 'authenticate' 
) ) );
$form->prepare ();

?>

		<div class="col-md-5">
					<?php echo $this->form()->openTag($form);?>
					<h4 class="nomargin">Sign In</h4>
						<p class="mt5 mb20">Login to access your account.</p>
            
						<?php echo $this->formRow($form->get('email_id'));?>
						<?php echo $this->formRow($form->get('password'));?>
						<?php echo $this->formSubmit($form->get('submit'));?>
           
						<?php
						if ($this->messages || $this->error_messages){
							$data = ($this->messages ? $this->messages : $this->error_messages); 
							$class = ($this->messages ? 'alert-success' : 'alert-warning alert-danger');
						?>
                <div class="mb20"></div>
                <div class="authentication__alert alert <?php echo $class;?>" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                	<?php 
                	echo '<ul>';
                	foreach($data as $message)
                	{
                		echo '<li>'.$message.'</li>';
                	}
                	echo '</ul>';
                	?>
                </div>
                <?php
                }
            ?><p><br/><a href="<?php echo $this->url('forgotpassword');?>">Forgot Password</a></p>
            <?php echo $this->form()->closeTag();?>
		</div>
<?php
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/guest_form_validations.js' );
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/jquery.validate.js' );
?>