<?php
$title = 'Reset Password';
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
		'resetpassword/process',
		array(
				'action'     => 'resetpasswordconfirm',
		)
));
$form->prepare();
?>


				<div class="col-md-5">
					<?php echo $this->form()->openTag($form);?>
					<h4 class="nomargin">Forgot Password</h4>
						<p class="mt5 mb20">Enter username to reset password.</p>
            
                <?php echo $this->formRow($form->get('password'));?>
				<?php echo $this->formRow($form->get('confirm_password'));?>
<input type="hidden" name="password_token" value="<?php echo $this->password_token; ?>">
			<?php echo $this->formSubmit($form->get('submit'));?>
           
           	<?php
                if ($this->messages || $this->error_messages){
                	$data = ($this->messages ? $this->messages : $this->error_messages); 
                	$class = ($this->messages ? 'alert-success' : 'alert-warning alert-danger');
                ?>
                <div class="mb20"></div>
                <div class="authentication__alert alert <?php echo $class;?>" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>
                	<?php 
                	echo '<ul>';
                	foreach($data as $message)
                	{
                		echo '<li>'.$message.'</li>';
                	}
                	echo '</ul>';
                	?>
                </div>
                <?php
                }
            ?><p><br/><a href="<?php echo $this->url('login'); ?>">Login</a></p>
            <?php echo $this->form()->closeTag();?>
				</div>
				<!-- col-sm-5 -->
<?php
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/guest_form_validations.js' );
$this->inlineScript ()->prependFile ( $this->basePath () . '/js/jquery.validate.js' );
?>