<?php $this->headTitle(($this->location_id ? 'Edit Location' : 'Add Location'));?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Location <span><?php echo ($this->location_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('dashboard');?>">Dashboard</a></li>
			<li><a href="<?php echo $this->basePath('user/location');?>">Location</a></li>
			<li class="active"><?php echo ($this->location_id ? 'Edit' : 'Add'); ?></li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <!-- a href="" class="panel-close">&times;</a -->
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->location_id ? 'Edit' : 'Add'); ?> Location</h4>
        </div>
		 <form id="addLocationForm" name="addLocationForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->location_id ? '<input type="hidden" value="'.$this->location_id.'" name="location_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Title<span class="asterisk">*</span></label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="title" id="title" value="<?php echo $this->location['title'];?>"/>
              </div>
            </div>    
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="pStatus" name="pStatus">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->location['status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->location_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->location_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/location');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php
	$this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/location.js' );
?>
