<?php $this->headTitle(($this->businessunit_id ? 'Edit Business Unit' : 'Add Business Unit'));

	if(isset($this->group['group_role']) and !empty($this->group['group_role'])) {
		$grouparray=$this->group['group_role'];
		$rolesarray = array_map(function ($grouparray) { return $grouparray['role_id']; }, $grouparray);
	} else {
		$rolesarray=array();
	}
?>
<div class="pageheader">
	<h2>
		<i class="fa fa-file"></i> Group <span><?php echo ($this->group_id ? 'Edit' : 'Add'); ?></span>
	</h2>
	<div class="breadcrumb-wrapper">
		<span class="label">You are here:</span>
		<ol class="breadcrumb">
			<li><a href="<?php echo $this->basePath('user');?>">User</a></li>
			<li><a href="<?php echo $this->basePath('user/group');?>">Group</a></li>
			<li class="active"><?php echo ($this->group_id ? 'Edit' : 'Add'); ?></li>
		</ol>
	</div>
</div>

<div class="contentpanel">
	<!-- content goes here... -->
	<div class="panel panel-default">

	<div class="panel-heading">
          <div class="panel-btns">
            <a href="" class="panel-close">&times;</a>
            <a href="" class="minimize">&minus;</a>
          </div>
          <h4 class="panel-title"><?php echo ($this->group_id ? 'Edit' : 'Add'); ?> Group</h4>
        </div>
		 <form id="addGroupForm" name="addGroupForm" class="form-horizontal form-bordered" method="POST" enctype="multipart/form-data">
        <div class="panel-body panel-body-nopadding">
            <?php echo ($this->group_id ? '<input type="hidden" value="'.$this->group_id.'" name="group_id" />' : '');?>
            <div class="form-group">
              <label class="col-sm-3 control-label">Title</label>
              <div class="col-sm-6">
                <input type="text" placeholder="Enter Title" class="form-control" name="title" id="title" value="<?php echo $this->group['title'];?>"/>
              </div>
            </div>
            <div class="form-group">
              
             <label class="col-sm-3 control-label">Description</label>
              <div class="col-sm-9">
               
               <textarea id="description" name="description" placeholder="Enter description here..." class="form-control" rows="10"><?php echo $this->group['description'];?></textarea>
              
              </div>
            </div>  
			<div class="form-group">
              
             <label class="col-sm-3 control-label">Levels</label>
              <div class="col-sm-4">
				   <select class="form-control mb15"  id="role" name="role[]" multiple="multiple">
						<?php
							foreach($this->role as $roles) {
								echo "<option value=".$roles['id'];
								if(in_array($roles['id'],$rolesarray)) { echo " selected='selected'"; }
								echo ">".$roles['title']."</option>";
							}
						?>
				   </select>
              </div>
            </div>   			
            <div class="form-group">
              <label class="col-sm-3 control-label">Status</label>
              <div class="col-sm-5">
               
                <select  class="form-control mb15" id="pStatus" name="pStatus">
                  <option value="1">Active</option>
                  <option value="0" <?php echo (!$this->group['status'] ? 'selected="selected"' : '');?>>Inactive</option>
                </select>
              
              </div>
            </div>
        </div><!-- panel-body -->
        <div class="panel-footer">
			 <div class="row">
				<div class="col-sm-6 col-sm-offset-3">
				  <input type="submit" data-after-loading-text="<?php echo ($this->group_id ? 'Update' : 'Add'); ?>" data-loading-text="Please Wait..." id="addPageBtn" name="addPageBtn" value="<?php echo ($this->group_id ? 'Update' : 'Add');?>" class="btn btn-primary">&nbsp;
				  <a href="<?php echo $this->basepath('user/group');?>" class="btn btn-default">Cancel</a>
				</div>
			 </div>
		  </div><!-- panel-footer -->
		  </form>
      </div>
</div><!-- contentpanel -->
<?php
    $this->inlineScript ()->prependFile ( $this->basePath () . '/js/user/group.js' );
?>